# Generated by Django 3.2.25 on 2024-05-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_purchaseorder_quality_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='acknowledgement_date',
            field=models.DateTimeField(null=True),
        ),
    ]
